parameters:
    ovh_logs.extra_fields: ~
    ovh_logs.port: 2202

services:
    _defaults:
        autowire: true
        public: true

    Chaplean\Bundle\OvhLogsBundle\Processor\OvhLogsProcessor:
        arguments:
            $token: '%ovh_logs.token%'
            $extraFields: '%ovh_logs.extra_fields%'
        tags:
            - { name: monolog.processor, method: processRecord, handler: 'ovh' }
