parameters:
    ovh_logs.env: null
    ovh_logs.port: 12201

services:
    _defaults:
        autowire: true
        public: true

    Chaplean\Bundle\OvhLogsBundle\Processor\OvhLogsProcessor:
        arguments:
            $token: '%ovh_logs.token%'
            $env: '%ovh_logs.env%'
        tags:
            - { name: monolog.processor, method: processRecord, handler: 'ovh' }
